# Generated by Django 5.2.3 on 2025-06-30 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_alter_products_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia zamówienia')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numer telefonu')),
                ('requires_delivery', models.BooleanField(default=False, verbose_name='Wymagana dostawa')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Adres dostawy')),
                ('payment_on_get', models.BooleanField(default=False, verbose_name='Metoda płatności')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Płatny')),
                ('status', models.CharField(default='In process', max_length=50, verbose_name='Status zamówienia')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Uzistkownik')),
            ],
            options={
                'verbose_name': 'Zamówienie',
                'verbose_name_plural': 'Zamówieny',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Imie')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cena')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Ilość')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia zamówienia')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='goods.products', verbose_name='Produkty')),
            ],
            options={
                'verbose_name': 'Sprzedane towary',
                'verbose_name_plural': 'Sprzedane towary',
                'db_table': 'order_item',
            },
        ),
    ]
